name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.32.11

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2

  fl_chart: ^0.70.0
  intl: ^0.20.1

  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  scoped_model: ^2.0.0
  shared_preferences: ^2.3.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  fluttertoast: ^8.2.8
  animated_text_kit: ^4.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/chair.png
    - assets/images/cat.png
    - assets/images/add.png
    - assets/images/idol.png
    - assets/images/P1.png
    - assets/images/FRwB.png
    - assets/images/LF.png
    - assets/images/LKoRK.png
    - assets/images/LR.png
    - assets/images/LS.png
    - assets/images/RKoLK.png
    - assets/images/RR.png
    - assets/images/UPwB.png
    - assets/images/UPwoB.png
    - assets/images/bk.png
    - assets/images/bk2.jpg
    - assets/images/Office_Chair.png
    - assets/images/BG3.jpg
    - assets/images/bluetooth.png
  fonts:
  - family: Rainbow
    fonts:
      - asset: fonts/Rainbow-Party-2.ttf
        style: italic


